### ISSUE TITLE
xmppipe being kicked from muc and not rejoining

### ISSUE THREAD

**Issue by jessiehowell** [msantos/xmppipe#9]
I am using xmppipe with openfire version 4.7.5 on redhat 8 linux. 

After about 90 minutes xmppipe is kicked from the muc with the following error:

`<presence from="muc@domain" to="muc@domain/xmppipe" type="unavailable"><x xmlns="http://jabber.org/protocol/muc#user"><item jid="xmppipe@domain/RESOURCE" affiliation="member" role="none"><reason>User seems to be unreachable (didn't respond to a ping request).</reason></item><status code="307"/><status code="110"/>`

xmppipe does not appear to be handling this ping at all, as I don't see it being received from the server in debug output.

I'll try and provide a packet capture to see if I can get the server ping. Alternately, you could probably check for code 307 and reconnect the muc whenever recieved.

**Comment by msantos** [comment]
@jessiehowell thanks for opening an issue about this! You're right, xmppipe didn't install a handler for server pings. Should be fixed in version 0.15.0, please let me know if you are still having problems or run into any other issues!

The [code 307](https://xmpp.org/registrar/mucstatus.html) is "Inform user that he or she has been kicked from the room".  I  run xmppipe under a supervisor so the xmppipe behaviour is usually to exit, get restarted by the supervisor and reconnect. In the case of MUC errors, it makes sense to rejoin. I'll look into handling the 307.
